'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import * as XLSX from "xlsx"
import { useRef } from "react"

type Product = {
  id: string
  name: string
  business_id: string
  stock_quantity: number
  min_stock_yellow: number
  min_stock_red: number
  price: number
  unit: string
  active: boolean
  barcode?: string
  code?: string
}

export default function ProductosPage() {
  const [products, setProducts] = useState<Product[]>([])
  const [newProductName, setNewProductName] = useState('')
  const [newStock, setNewStock] = useState(0)
  const [newMinStock, setNewMinStock] = useState(1)
  const [loading, setLoading] = useState(false)
  const [newUnit, setNewUnit] = useState('unidad')

  const [isOpen, setIsOpen] = useState(false)
  const [newPrice, setNewPrice] = useState(0)
  const [newActive, setNewActive] = useState(true)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [selectedBusinessId, setSelectedBusinessId] = useState<string | null>(null)
  const [searchTerm, setSearchTerm] = useState('')
  const fileInputRef = useRef<HTMLInputElement | null>(null)
  const [newBarcode, setNewBarcode] = useState('')
  const [newCode, setNewCode] = useState('')
  const [toast, setToast] = useState<{
  type: "success" | "error"
  message: string
} | null>(null)

const generateEAN13 = () => {

  const base = Array.from({ length: 12 }, () =>
    Math.floor(Math.random() * 10)
  )

  const sum = base.reduce((acc, num, i) => {
    return acc + num * (i % 2 === 0 ? 1 : 3)
  }, 0)

  const checkDigit = (10 - (sum % 10)) % 10

  const ean = [...base, checkDigit].join('')

  setNewBarcode(ean)

  return ean
}

useEffect(() => {
  const id = localStorage.getItem('activeBusinessId')

  console.log("ID desde localStorage:", id)

  if (id) {
    setSelectedBusinessId(id)
  } else {
    console.log("No hay business activo")
  }
}, [])


  const fetchProducts = async () => {
    if (!selectedBusinessId) return

    setLoading(true)

    const { data } = await supabase
      .from('products')
      .select('*')
      .eq('business_id', selectedBusinessId)
      .order('created_at', { ascending: false })

    setProducts(data || [])
    setLoading(false)
  }

const createProduct = async () => {
  if (!newProductName.trim()) {
    setToast({ type: "error", message: "Ingresá un nombre válido" })
    return
  }

  try {

     const barcodeToUse = newBarcode || generateEAN13()
     const autoGenerated = !newBarcode

    if (editingId) {
      const { error } = await supabase
        .from('products')
        .update({
  name: newProductName,
  unit: newUnit,
  stock_quantity: newStock,
  min_stock_yellow: newMinStock,
  min_stock_red: Math.max(1, Math.floor(newMinStock / 2)),
  price: newPrice,
  active: newActive,
  code: newCode || null,
  barcode: barcodeToUse,
})
        .eq('id', editingId)

     if (error) throw error

if (autoGenerated) {
  setToast({
    type: "success",
    message: "Producto actualizado. Arcana generó un código de barras automáticamente."
  })
} else {
  setToast({
    type: "success",
    message: "Producto actualizado correctamente"
  })
}

setEditingId(null)

      } else {

      const { error } = await supabase
        .from('products')
    .insert({
  name: newProductName,
  business_id: selectedBusinessId,
  unit: newUnit,
  stock_quantity: newStock,
  min_stock_yellow: newMinStock,
  min_stock_red: Math.max(1, Math.floor(newMinStock / 2)),
  price: newPrice,
  active: newActive,
  code: newCode || null,
  barcode: barcodeToUse,
})

      if (error) throw error

      setToast({ type: "success", message: "Producto creado correctamente" })
    }

    setNewProductName('')
    setNewUnit('unidad')
    setNewStock(0)
    setNewMinStock(1)
    setNewPrice(0)
    setNewActive(true)
    setIsOpen(false)
    setNewCode('')
    setNewBarcode('')
    fetchProducts()

  } catch (err: any) {
    setToast({ type: "error", message: err.message || "Error al guardar producto" })
  }
}


 useEffect(() => {
  if (selectedBusinessId) {
    fetchProducts()
  }
}, [selectedBusinessId])

const updatePrice = async (id: string, newPrice: number) => {
  await supabase
    .from('products')
    .update({ price: newPrice })
    .eq('id', id)

  fetchProducts()
}

const handleDelete = async (id: string) => {
  if (!confirm("¿Eliminar producto?")) return

  await supabase
    .from('products')
    .delete()
    .eq('id', id)

  fetchProducts()
}
const handleEdit = (product: Product) => {
  setEditingId(product.id)
  setNewProductName(product.name)
  setNewPrice(product.price)
  setNewStock(product.stock_quantity)
  setNewMinStock(product.min_stock_yellow)
  setNewUnit(product.unit)
  setNewActive(product.active)
  setNewCode(product.code || '')
  setNewBarcode(product.barcode || '')
  setIsOpen(true)
}

useEffect(() => {
  if (!toast) return

  const timer = setTimeout(() => {
    setToast(null)
  }, 2500)

  return () => clearTimeout(timer)
}, [toast])

const handleExcelUpload = async (e: any) => {

  const file = e.target.files[0]

  if (!file) return

  const data = await file.arrayBuffer()

  const workbook = XLSX.read(data)

  const sheet = workbook.Sheets[workbook.SheetNames[0]]

  const rows: any[] = XLSX.utils.sheet_to_json(sheet)

  console.log(rows)
  
  const requiredFields = ["name", "price", "stock"]

for (const field of requiredFields) {
  if (!rows[0] || !(field in rows[0])) {
    setToast({
      type: "error",
      message: `El Excel debe tener la columna "${field}"`
    })
    return
  }
}

for (const row of rows) {

  const generatedCode = `PRD-${Date.now()}-${Math.floor(Math.random() * 1000)}`

  const productName = row.name.trim().toLowerCase()

  const { data } = await supabase
    .from("products")
    .select("*")
    .eq("business_id", selectedBusinessId)

  const existing = data?.find(
    p => p.name.trim().toLowerCase() === productName
  )

 if (existing) {
  await supabase
    .from("products")
    .update({
      stock_quantity: existing.stock_quantity + Number(row.stock),
      min_stock_yellow: row.min_stock_yellow
        ? Number(row.min_stock_yellow)
        : existing.min_stock_yellow,
      min_stock_red: row.min_stock_yellow
        ? Math.max(1, Math.floor(Number(row.min_stock_yellow) / 2))
        : existing.min_stock_red,
      code: row.code || existing.code,
    })
    .eq("id", existing.id)
} else {

 await supabase.from("products").insert({
  name: row.name.trim(),
  price: Number(row.price),
  stock_quantity: Number(row.stock),
  unit: row.unit || "unidad",
  code: row.code || generatedCode,
  min_stock_yellow: row.min_stock_yellow ? Number(row.min_stock_yellow) : 1,
  min_stock_red: row.min_stock_yellow
    ? Math.max(1, Math.floor(Number(row.min_stock_yellow) / 2))
    : 1,
  business_id: selectedBusinessId
})
  }

}

  fetchProducts()

  setToast({
    type: "success",
    message: "Productos importados correctamente"
  })

}

const downloadTemplate = () => {
  const rows = [
    { name: "Blazer Negro Clásico", price: 89900, stock: 5, unit: "unidad" },
    { name: "Traje Femenino Gris Perla", price: 132500, stock: 2, unit: "unidad" },
    { name: "Pantalón Sastrero Nude", price: 64500, stock: 4, unit: "unidad" },
  ]

  const worksheet = XLSX.utils.json_to_sheet(rows)
  const workbook = XLSX.utils.book_new()

  XLSX.utils.book_append_sheet(workbook, worksheet, "productos")

  XLSX.writeFile(workbook, "plantilla_productos_arcana.xlsx")
}

  return (
  <div className="p-4 md:p-6 space-y-6 md:space-y-8">


  <input
  type="file"
  accept=".xlsx,.xls"
  ref={fileInputRef}
  onChange={handleExcelUpload}
  style={{ display: "none" }}
/>
   

{toast && (
  <div
    className={`mb-4 p-4 rounded-xl text-sm font-medium
      ${toast.type === "success"
        ? "bg-green-900 text-green-400 border border-green-700"
        : "bg-red-900 text-red-400 border border-red-700"
      }`}
  >
    {toast.message}
  </div>

)}
{/* HEADER */}
<div className="flex flex-col md:flex-row md:justify-between md:items-center gap-4">

  <div>
    <h1 className="text-2xl font-semibold text-white">
      📦 Productos
    </h1>
    <p className="text-gray-400 mt-1">
      Gestioná tu catálogo y stock.
    </p>
  </div>

  <div className="flex flex-col sm:flex-row gap-3 w-full md:w-auto">

    <button
      onClick={() => fileInputRef.current?.click()}
     className="w-full sm:w-auto bg-[#6C5CE7] hover:bg-[#5A4BD1] transition rounded-xl px-5 py-3 font-semibold"
      
    >
      📥 Importar
    </button>

    <button
      onClick={() => setIsOpen(true)}
      className="w-full sm:w-auto bg-[#1F6BFF] hover:bg-[#2E7BFF] transition rounded-xl px-5 py-3 font-semibold"
    >
      ➕ Nuevo producto
    </button>

  </div>

</div>   {/* ← ACA SE CIERRA EL HEADER */}

{/* BUSCADOR */}
<div className="mt-4 mb-4">

  <input
    type="text"
    placeholder="Buscar producto..."
    className="bg-[#0B0B10] border border-[#2A2A32] rounded-xl px-4 py-3 text-white w-full md:w-64 focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40"
    onChange={(e) => setSearchTerm(e.target.value)}
  />

</div>

    

    {/* TABLA */}
    <div className="bg-[#14141A] border border-[#1F1F24] rounded-2xl overflow-hidden">
  <div className="overflow-x-auto">
    <div className="max-h-[500px] overflow-y-auto min-w-[720px]">
      <table className="w-full text-sm">

        <thead className="bg-[#0F0F14] text-gray-400">
  <tr className="text-left">
    <th className="p-4">Producto</th>
    <th className="p-4">Precio</th>
    <th className="p-4">Stock</th>
    <th className="p-4">Estado</th>
    <th className="p-4">Código</th>
    <th className="p-4 text-center">Acciones</th>
          </tr>
        </thead>

        <tbody>

          {products.filter((p) =>
  p.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
  (p.barcode && p.barcode.includes(searchTerm)) ||
  (p.code && p.code.includes(searchTerm))
)
  .map((p) => {
            let estado = 'Disponible'
            let color = 'green'

            if (p.stock_quantity === 0) {
              estado = 'Agotado'
              color = 'red'
            } else if (p.stock_quantity <= p.min_stock_yellow) {
              estado = 'Bajo stock'
              color = 'yellow'
            }

            return (
              <tr
                key={p.id}
                className="border-t border-[#1F1F24] hover:bg-[#101018] transition"
              >
               <td className="p-4 text-white font-medium">
  {p.name}
</td>

<td className="p-4 font-semibold text-[#1F6BFF]">
  ${Number(p.price).toLocaleString()}
</td>

<td className="p-4 font-bold text-lg text-white">
  {p.stock_quantity}
</td>

<td className="p-4">
  <span
    className={`px-3 py-1 rounded-full text-xs ${
      color === 'green'
        ? 'bg-green-500/10 text-green-400'
        : color === 'yellow'
        ? 'bg-yellow-500/10 text-yellow-400'
        : 'bg-red-500/10 text-red-400'
    }`}
  >
    {estado}
  </span>
</td>

<td className="p-4 text-gray-400 text-xs">
 {p.code || p.barcode || "—"}
</td>

<td className="p-4">
  <div className="flex gap-3 justify-center">
    <button
      onClick={() => handleEdit(p)}
      className="text-blue-400 hover:text-blue-300 transition text-sm"
    >
      ✏️ Editar
    </button>

    <button
      onClick={() => handleDelete(p.id)}
      className="text-red-400 hover:text-red-300 transition text-sm"
    >
      🗑 Eliminar
    </button>
  </div>
</td> 
              </tr>
            )
          })}

        </tbody>

      </table>
</div>
</div>

     {products.length === 0 && (
  <div className="p-6 md:p-8">
    <div className="bg-[#101018] border border-[#1F1F24] rounded-2xl p-6 md:p-8">
      <h3 className="text-white text-lg md:text-xl font-semibold mb-2">
        Empezá cargando tus productos
      </h3>

      <p className="text-gray-400 text-sm md:text-base mb-6 max-w-2xl">
        Podés cargarlos uno por uno desde el botón <span className="text-white font-medium">Nuevo producto</span> o importar varios juntos usando un archivo Excel.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
        <div className="bg-[#0B0B10] border border-[#1F1F24] rounded-xl p-5">
          <h4 className="text-white font-semibold mb-2">Carga manual</h4>
          <p className="text-gray-400 text-sm mb-4">
            Ideal si recién empezás o si tenés pocos productos.
          </p>

          <button
            onClick={() => setIsOpen(true)}
            className="w-full sm:w-auto bg-[#1F6BFF] hover:bg-[#2E7BFF] transition rounded-xl px-5 py-3 font-semibold"
          >
            ➕ Nuevo producto
          </button>
        </div>

        <div className="bg-[#0B0B10] border border-[#1F1F24] rounded-xl p-5">
          <h4 className="text-white font-semibold mb-2">Importar desde Excel</h4>
          <p className="text-gray-400 text-sm mb-4">
            Usá la plantilla básica de Arcana para importar tus productos sin errores.
          </p>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={downloadTemplate}
              className="w-full sm:w-auto bg-gradient-to-r from-purple-600 to-indigo-600 hover:opacity-90 transition rounded-xl px-5 py-3 font-semibold text-white shadow-lg shadow-purple-500/20"
            >
              ⬇ Descargar plantilla
            </button>

            <button
              onClick={() => fileInputRef.current?.click()}
              className="w-full sm:w-auto bg-[#6C5CE7] hover:bg-[#5A4BD1] transition rounded-xl px-5 py-3 font-semibold"
            >
              📥 Importar Excel
            </button>
          </div>
        </div>
      </div>

      <div className="bg-[#0B0B10] border border-dashed border-[#2A2A32] rounded-xl p-4">
        <p className="text-sm text-gray-300 mb-2 font-medium">
          Tu archivo Excel debe tener estas columnas:
        </p>

        <div className="flex flex-wrap gap-2 mb-3">
          <span className="px-3 py-1 rounded-full bg-[#1A1A22] text-gray-300 text-xs">name</span>
          <span className="px-3 py-1 rounded-full bg-[#1A1A22] text-gray-300 text-xs">price</span>
          <span className="px-3 py-1 rounded-full bg-[#1A1A22] text-gray-300 text-xs">stock</span>
          <span className="px-3 py-1 rounded-full bg-[#1A1A22] text-gray-300 text-xs">unit</span>
        </div>

        <p className="text-xs text-gray-500">
          Ejemplo: una fila por producto, sin cambiar los nombres de las columnas.
        </p>
      </div>
    </div>
  </div>
)}

    </div>
{isOpen && (
  <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
  <div className="bg-[#14141A] border border-[#1F1F24] rounded-2xl p-5 md:p-8 w-full max-w-md max-h-[90vh] overflow-y-auto space-y-6">

      <h2 className="text-2xl font-semibold text-white">
        Nuevo producto
      </h2>

      <div className="space-y-5">

        {/* Nombre */}
        <div className="space-y-1">
          <label className="text-sm text-gray-400">
            Nombre del producto
          </label>
          <input
            value={newProductName}
            onChange={(e) => setNewProductName(e.target.value)}
            className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
            focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
          />
        </div>

        {/* Unidad */}
        <div className="space-y-1">
          <label className="text-sm text-gray-400">
            Unidad de venta
          </label>
          <select
            value={newUnit}
            onChange={(e) => setNewUnit(e.target.value)}
            className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
            focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
          >
            <option value="unidad">Unidad</option>
            <option value="kg">Kilo</option>
            <option value="litro">Litro</option>
            <option value="pack">Pack</option>
          </select>
        </div>

        {/* Precio */}
        <div className="space-y-1">
          <label className="text-sm text-gray-400">
            Precio de venta
          </label>

          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">
              $
            </span>

            <input
              type="number"
              placeholder="Ej: 15000"
              value={newPrice}
              onChange={(e) => setNewPrice(Number(e.target.value))}
              className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl 
              p-3 pl-8 text-white
              focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
            />
          </div>
        </div>

        {/* Stock inicial */}
        <div className="space-y-1">
          <label className="text-sm text-gray-400">
            Stock inicial
          </label>
          <input
            type="number"
            placeholder="Cantidad disponible al cargar"
            value={newStock}
            onChange={(e) => setNewStock(Number(e.target.value))}
            className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
            focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
          />
        </div>

        {/* Stock mínimo */}
        <div className="space-y-1">
          <label className="text-sm text-gray-400">
            Stock mínimo (alerta)
          </label>
          <input
            type="number"
            min={1}
            placeholder="Ej: 5"
            value={newMinStock}
            onChange={(e) =>
              setNewMinStock(Math.max(1, Number(e.target.value)))
            }
            className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
            focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
          />
        </div>

{/* Código interno */}
<div className="space-y-1">
  <label className="text-sm text-gray-400">
    Código del producto (opcional)
  </label>

  <input
    value={newCode}
    onChange={(e) => setNewCode(e.target.value)}
    placeholder="Ej: VEL-202"
    className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
    focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
  />
</div>

{/* Barcode */}

<div className="space-y-1">
  <label className="text-sm text-gray-400">
    Código de barras (opcional)
  </label>

  <div className="flex gap-2">

    <input
      value={newBarcode}
      onChange={(e) => setNewBarcode(e.target.value)}
      placeholder="Ej: 7791234567890"
      className="flex-1 bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
      focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
    />

    <button
      type="button"
      onClick={generateEAN13}
      className="px-3 bg-[#2A2A32] rounded-xl hover:bg-[#333]"
    >
      ⚡ Generar
    </button>

  </div>
</div>

        {/* Activo */}
        <div className="flex items-center gap-3 pt-2">
          <input
            type="checkbox"
            checked={newActive}
            onChange={(e) => setNewActive(e.target.checked)}
          />
          <label className="text-sm text-gray-400">
            Producto activo
          </label>
        </div>

      </div>

      {/* Botones */}
      <div className="flex flex-col-reverse sm:flex-row justify-end gap-3 pt-4">
        <button
          onClick={() => setIsOpen(false)}
          className="w-full sm:w-auto px-4 py-2 rounded-xl border border-[#2A2A32] bg-[#1A1A22] text-white hover:bg-[#22222B] hover:border-[#3A3A48] transition"
        >
          Cancelar
        </button>

        <button
          onClick={createProduct}
          className="w-full sm:w-auto bg-[#1F6BFF] hover:bg-[#2E7BFF] transition px-5 py-2 rounded-xl font-semibold"
        >
          Guardar
        </button>
            </div>
    </div>
  </div>
)}
  </div>

)
}
