'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import * as XLSX from "xlsx"
import { useRef } from "react"

type Product = {
  id: string
  name: string
  business_id: string
  stock_quantity: number
  min_stock_yellow: number
  min_stock_red: number
  price: number
  unit: string
  active: boolean
  barcode?: string
  code?: string
  supplier_id?: string | null
  cost_price?: number
  sale_type?: 'unit' | 'weight'
  unit_base?: string
  price_by?: string
  suppliers?: {
   name: string
} | null
}

type Supplier = {
  id: string
  name: string
}

export default function ProductosPage() {
  const [products, setProducts] = useState<Product[]>([])
  const [newProductName, setNewProductName] = useState('')
  const [newMinStock, setNewMinStock] = useState('')
  const [loading, setLoading] = useState(false)
  const [newUnit, setNewUnit] = useState('unidad')
  const [newStock, setNewStock] = useState('')
  const [newPrice, setNewPrice] = useState('')
  const [newCostPrice, setNewCostPrice] = useState('')
  const [isOpen, setIsOpen] = useState(false)
  
  const [newActive, setNewActive] = useState(true)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [selectedBusinessId, setSelectedBusinessId] = useState<string | null>(null)
  const [searchTerm, setSearchTerm] = useState('')
  const fileInputRef = useRef<HTMLInputElement | null>(null)
  const [newBarcode, setNewBarcode] = useState('')
  const [newCode, setNewCode] = useState('')
  const [suppliers, setSuppliers] = useState<Supplier[]>([])
  const [newSupplierId, setNewSupplierId] = useState('')
  const [newSaleType, setNewSaleType] = useState<'unit' | 'weight'>('unit')
  const [newUnitBase, setNewUnitBase] = useState('unidad')
  const [newPriceBy, setNewPriceBy] = useState<'kg' | '100g'>('kg')
  const [newPackageWeightKg, setNewPackageWeightKg] = useState('')
  const [newPackageCost, setNewPackageCost] = useState('')
  const [toast, setToast] = useState<{
  type: "success" | "error"
  message: string
} | null>(null)

const generateEAN13 = () => {

  const base = Array.from({ length: 12 }, () =>
    Math.floor(Math.random() * 10)
  )

  const sum = base.reduce((acc, num, i) => {
    return acc + num * (i % 2 === 0 ? 1 : 3)
  }, 0)

  const checkDigit = (10 - (sum % 10)) % 10

  const ean = [...base, checkDigit].join('')

  setNewBarcode(ean)

  return ean
}

useEffect(() => {
  const id = localStorage.getItem('activeBusinessId')

  console.log("ID desde localStorage:", id)

  if (id) {
    setSelectedBusinessId(id)
  } else {
    console.log("No hay business activo")
  }
}, [])


  const fetchProducts = async () => {
    if (!selectedBusinessId) return

    setLoading(true)

    const { data } = await supabase
      .from('products')
      .select('*, suppliers(name)')
      .eq('business_id', selectedBusinessId)
      .order('created_at', { ascending: false })

    setProducts(data || [])
    setLoading(false)
  }

  const fetchSuppliers = async () => {
  if (!selectedBusinessId) return

  const { data, error } = await supabase
    .from('suppliers')
    .select('id, name')
    .eq('business_id', selectedBusinessId)
    .order('name', { ascending: true })

  if (error) {
    console.error('Error cargando proveedores:', error)
    return
  }

  setSuppliers(data || [])
}

const parseMoney = (value: string) => {
  return Number(value.replace(/\./g, '').replace(',', '.')) || 0
}

const formatMoneyInput = (value: string) => {
  const onlyNumbers = value.replace(/\D/g, '')

  if (!onlyNumbers) return ''

  return Number(onlyNumbers).toLocaleString('es-AR')
}

const createProduct = async () => {
  if (!newProductName.trim()) {
    setToast({ type: "error", message: "Ingresá un nombre válido" })
    return
  }

  try {

     const barcodeToUse = newBarcode || generateEAN13()
     const autoGenerated = !newBarcode

   if (editingId) {
  const { error } = await supabase
    .from('products')
    .update({
      name: newProductName,
      unit: newUnit,
      stock_quantity: Number(newStock || 0),
      min_stock_yellow: Number(newMinStock || 1),
      min_stock_red: Math.max(1, Math.floor(Number(newMinStock || 1) / 2)),
      price: parseMoney(newPrice),
      active: newActive,
      code: newCode || null,
      barcode: barcodeToUse,
      supplier_id: newSupplierId || null,
      cost_price: parseMoney(newCostPrice),
      sale_type: newSaleType,
      unit_base: newSaleType === 'weight' ? 'kg' : 'unit',
      price_by: newSaleType === 'weight' ? newPriceBy : 'unit',
    })
    .eq('id', editingId)

     if (error) throw error

if (autoGenerated) {
  setToast({
    type: "success",
    message: "Producto actualizado. Arcana generó un código de barras automáticamente."
  })
} else {
  setToast({
    type: "success",
    message: "Producto actualizado correctamente"
  })
}

setEditingId(null)

      } else {

      const { error } = await supabase
        .from('products')
    .insert({
  name: newProductName,
  business_id: selectedBusinessId,
  unit: newUnit,
  stock_quantity: Number(newStock || 0),
  min_stock_yellow: newMinStock,
  min_stock_red: Math.max(1, Math.floor(Number(newMinStock || 1) / 2)),
  price: parseMoney(newPrice),
  active: newActive,
  code: newCode || null,
  barcode: barcodeToUse,
  supplier_id: newSupplierId || null,
  cost_price: parseMoney(newCostPrice),
  sale_type: newSaleType,
  unit_base: newSaleType === 'weight' ? 'kg' : 'unit',
  price_by: newSaleType === 'weight' ? newPriceBy : 'unit',
})

      if (error) throw error

      setToast({ type: "success", message: "Producto creado correctamente" })
    }

    setNewProductName('')
    setNewUnit('unidad')
    setNewStock('')
    setNewMinStock('')
    setNewPrice('')
    setNewActive(true)
    setIsOpen(false)
    setNewCode('')
    setNewBarcode('')
    setNewSupplierId('')
    setNewCostPrice('')
    fetchProducts()

  } catch (err: any) {
    setToast({ type: "error", message: err.message || "Error al guardar producto" })
  }
}


 useEffect(() => {
  if (selectedBusinessId) {
    fetchProducts()
    fetchSuppliers()
  }
}, [selectedBusinessId])

const updatePrice = async (id: string, newPrice: number) => {
  await supabase
    .from('products')
    .update({ price: newPrice })
    .eq('id', id)

  fetchProducts()
}

const handleDelete = async (id: string) => {
  if (!confirm("¿Eliminar producto?")) return

  await supabase
    .from('products')
    .delete()
    .eq('id', id)

  fetchProducts()
}
const handleEdit = (product: Product) => {
  setEditingId(product.id)
  setNewProductName(product.name)
  setNewPrice(String(product.price || ''))
  setNewStock(String(product.stock_quantity || ''))
  setNewMinStock(String(product.min_stock_yellow || ''))
  setNewUnit(product.unit)
  setNewActive(product.active)
  setNewCode(product.code || '')
  setNewBarcode(product.barcode || '')
  setNewSupplierId(product.supplier_id || '')
  setNewCostPrice(String(product.cost_price || ''))
  setNewSaleType(product.sale_type || 'unit')
  setNewUnitBase(product.unit_base || 'unidad')
  setIsOpen(true)
  setNewPriceBy(
  product.price_by === '100g' ? '100g' : 'kg'
)
}

useEffect(() => {
  if (!toast) return

  const timer = setTimeout(() => {
    setToast(null)
  }, 2500)

  return () => clearTimeout(timer)
}, [toast])

const handleExcelUpload = async (e: any) => {

  const file = e.target.files[0]

  if (!file) return

  const data = await file.arrayBuffer()

  const workbook = XLSX.read(data)

  const sheet = workbook.Sheets[workbook.SheetNames[0]]

  const rows: any[] = XLSX.utils.sheet_to_json(sheet)

  console.log(rows)
  
  const requiredFields = ["name", "price", "stock"]

for (const field of requiredFields) {
  if (!rows[0] || !(field in rows[0])) {
    setToast({
      type: "error",
      message: `El Excel debe tener la columna "${field}"`
    })
    return
  }
}

for (const row of rows) {

  const generatedCode = `PRD-${Date.now()}-${Math.floor(Math.random() * 1000)}`

  const productName = row.name.trim().toLowerCase()

  const { data } = await supabase
    .from("products")
    .select("*")
    .eq("business_id", selectedBusinessId)

  const existing = data?.find(
    p => p.name.trim().toLowerCase() === productName
  )

 if (existing) {
  await supabase
    .from("products")
    .update({
      stock_quantity: existing.stock_quantity + Number(row.stock),
      min_stock_yellow: row.min_stock_yellow
        ? Number(row.min_stock_yellow)
        : existing.min_stock_yellow,
      min_stock_red: row.min_stock_yellow
        ? Math.max(1, Math.floor(Number(row.min_stock_yellow) / 2))
        : existing.min_stock_red,
      code: row.code || existing.code,
    })
    .eq("id", existing.id)
} else {

 await supabase.from("products").insert({
  name: row.name.trim(),
  price: Number(row.price),
  stock_quantity: Number(row.stock),
  unit: row.unit || "unidad",
  code: row.code || generatedCode,
  min_stock_yellow: row.min_stock_yellow ? Number(row.min_stock_yellow) : 1,
  min_stock_red: row.min_stock_yellow
    ? Math.max(1, Math.floor(Number(row.min_stock_yellow) / 2))
    : 1,
  business_id: selectedBusinessId
})
  }

}

  fetchProducts()

  setToast({
    type: "success",
    message: "Productos importados correctamente"
  })

}

const downloadTemplate = () => {
  const rows = [
    {
      name: "Blazer Negro Clásico",
      price: 89900,
      stock: 5,
      unit: "unidad",
      code: "ARC-001",
      min_stock_yellow: 3,
    },
    {
      name: "Traje Femenino Gris Perla",
      price: 132500,
      stock: 2,
      unit: "unidad",
      code: "ARC-002",
      min_stock_yellow: 2,
    },
    {
      name: "Pantalón Sastrero Nude",
      price: 64500,
      stock: 4,
      unit: "unidad",
      code: "ARC-003",
      min_stock_yellow: 2,
    },
  ]

  const worksheet = XLSX.utils.json_to_sheet(rows)
  const workbook = XLSX.utils.book_new()

  XLSX.utils.book_append_sheet(workbook, worksheet, "productos")
  XLSX.writeFile(workbook, "plantilla_productos_arcana.xlsx")
}

  return (
  <div className="p-4 md:p-6 space-y-6 md:space-y-8">


  <input
  type="file"
  accept=".xlsx,.xls"
  ref={fileInputRef}
  onChange={handleExcelUpload}
  style={{ display: "none" }}
/>
   

{toast && (
  <div
    className={`mb-4 p-4 rounded-xl text-sm font-medium
      ${toast.type === "success"
        ? "bg-green-900 text-green-400 border border-green-700"
        : "bg-red-900 text-red-400 border border-red-700"
      }`}
  >
    {toast.message}
  </div>

)}
{/* HEADER */}
<div className="flex flex-col md:flex-row md:justify-between md:items-center gap-4">

  <div>
    <h1 className="text-2xl font-semibold text-white">
      📦 Productos
    </h1>
    <p className="text-gray-400 mt-1">
      Gestioná tu catálogo y stock.
    </p>
  </div>

  <div className="flex flex-col sm:flex-row gap-3 w-full md:w-auto">

    <button
      onClick={() => fileInputRef.current?.click()}
     className="w-full sm:w-auto bg-[#6C5CE7] hover:bg-[#5A4BD1] transition rounded-xl px-5 py-3 font-semibold"
      
    >
      📥 Importar
    </button>

    <button
      onClick={() => setIsOpen(true)}
      className="w-full sm:w-auto bg-[#1F6BFF] hover:bg-[#2E7BFF] transition rounded-xl px-5 py-3 font-semibold"
    >
      ➕ Nuevo producto
    </button>

  </div>

</div>   {/* ← ACA SE CIERRA EL HEADER */}

{/* BUSCADOR */}
<div className="mt-4 mb-4">

  <input
    type="text"
    placeholder="Buscar producto..."
    className="bg-[#0B0B10] border border-[#2A2A32] rounded-xl px-4 py-3 text-white w-full md:w-64 focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40"
    onChange={(e) => setSearchTerm(e.target.value)}
  />

</div>

    

    {/* TABLA */}
    <div className="bg-[#14141A] border border-[#1F1F24] rounded-2xl overflow-hidden">
  <div className="overflow-x-auto">
    <div className="max-h-[500px] overflow-y-auto min-w-[720px]">
      <table className="w-full text-sm">

        <thead className="bg-[#0F0F14] text-gray-400">
  <tr className="text-left">
    <th className="p-4">Producto</th>
    <th className="p-4">Precio</th>
    <th className="p-4">Costo</th>
    <th className="p-4">Margen</th>
    <th className="p-4">Proveedor</th>
    <th className="p-4">Stock</th>
    <th className="p-4">Estado</th>
    <th className="p-4">Código</th>
    <th className="p-4 text-center">Acciones</th>
          </tr>
        </thead>

        <tbody>

          {products.filter((p) =>
  p.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
  (p.barcode && p.barcode.includes(searchTerm)) ||
  (p.code && p.code.includes(searchTerm))
)
  .map((p) => {
            let estado = 'Disponible'
            let color = 'green'

            if (p.stock_quantity === 0) {
              estado = 'Agotado'
              color = 'red'
            } else if (p.stock_quantity <= p.min_stock_yellow) {
              estado = 'Bajo stock'
              color = 'yellow'
            }

            return (
              <tr
                key={p.id}
                className="border-t border-[#1F1F24] hover:bg-[#101018] transition"
              >
               <td className="p-4 text-white font-medium">
  {p.name}
</td>

<td className="p-4 font-semibold text-[#1F6BFF]">
  ${Number(p.price).toLocaleString()}
</td>

<td className="p-4 text-gray-300">
  ${Number(p.cost_price || 0).toLocaleString()}
</td>

<td className="p-4 font-semibold text-green-400">
  ${Number((p.price || 0) - (p.cost_price || 0)).toLocaleString()}
</td>

<td className="p-4 text-gray-400">
  {p.suppliers?.name || '—'}
</td>

<td className="p-4 font-bold text-lg text-white">
  {p.stock_quantity}
</td>

<td className="p-4">
  <span
    className={`px-3 py-1 rounded-full text-xs ${
      color === 'green'
        ? 'bg-green-500/10 text-green-400'
        : color === 'yellow'
        ? 'bg-yellow-500/10 text-yellow-400'
        : 'bg-red-500/10 text-red-400'
    }`}
  >
    {estado}
  </span>
</td>

<td className="p-4 text-gray-400 text-xs">
 {p.code || p.barcode || "—"}
</td>

<td className="p-4">
  <div className="flex gap-3 justify-center">
    <button
      onClick={() => handleEdit(p)}
      className="text-blue-400 hover:text-blue-300 transition text-sm"
    >
      ✏️ Editar
    </button>

    <button
      onClick={() => handleDelete(p.id)}
      className="text-red-400 hover:text-red-300 transition text-sm"
    >
      🗑 Eliminar
    </button>
  </div>
</td> 
              </tr>
            )
          })}

        </tbody>

      </table>
</div>
</div>

     {products.length === 0 && (
  <div className="p-6 md:p-8">
    <div className="bg-[#101018] border border-[#1F1F24] rounded-2xl p-6 md:p-8">
      <h3 className="text-white text-lg md:text-xl font-semibold mb-2">
        Empezá cargando tus productos
      </h3>

      <p className="text-gray-400 text-sm md:text-base mb-6 max-w-2xl">
        Podés cargarlos uno por uno desde el botón <span className="text-white font-medium">Nuevo producto</span> o importar varios juntos usando un archivo Excel.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
        <div className="bg-[#0B0B10] border border-[#1F1F24] rounded-xl p-5">
          <h4 className="text-white font-semibold mb-2">Carga manual</h4>
          <p className="text-gray-400 text-sm mb-4">
            Ideal si recién empezás o si tenés pocos productos.
          </p>

          <button
            onClick={() => setIsOpen(true)}
            className="w-full sm:w-auto bg-[#1F6BFF] hover:bg-[#2E7BFF] transition rounded-xl px-5 py-3 font-semibold"
          >
            ➕ Nuevo producto
          </button>
        </div>

        <div className="bg-[#0B0B10] border border-[#1F1F24] rounded-xl p-5">
          <h4 className="text-white font-semibold mb-2">Importar desde Excel</h4>
          <p className="text-gray-400 text-sm mb-4">
            Usá la plantilla básica de Arcana para importar tus productos sin errores.
          </p>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={downloadTemplate}
              className="w-full sm:w-auto bg-gradient-to-r from-purple-600 to-indigo-600 hover:opacity-90 transition rounded-xl px-5 py-3 font-semibold text-white shadow-lg shadow-purple-500/20"
            >
              ⬇ Descargar plantilla
            </button>

            <button
              onClick={() => fileInputRef.current?.click()}
              className="w-full sm:w-auto bg-[#6C5CE7] hover:bg-[#5A4BD1] transition rounded-xl px-5 py-3 font-semibold"
            >
              📥 Importar Excel
            </button>
          </div>
        </div>
      </div>

      <div className="bg-[#0B0B10] border border-dashed border-[#2A2A32] rounded-xl p-5 md:p-6">
  <div className="mb-4">
    <p className="text-sm md:text-base text-gray-200 font-semibold">
      Cómo debe estar armado tu Excel
    </p>
    <p className="text-xs md:text-sm text-gray-400 mt-1">
      Arcana puede importar productos desde una planilla simple. Para empezar, no necesitás completar todo.
    </p>
  </div>

  <div className="mb-5">
    <p className="text-xs uppercase tracking-wide text-gray-500 mb-2">
      Columnas obligatorias
    </p>

    <div className="flex flex-wrap gap-2 mb-3">
      <span
        title="Nombre del producto"
        className="px-3 py-1 rounded-full bg-[#1A1A22] text-white text-xs border border-[#2A2A32]"
      >
        name
      </span>

      <span
        title="Precio de venta"
        className="px-3 py-1 rounded-full bg-[#1A1A22] text-white text-xs border border-[#2A2A32]"
      >
        price
      </span>

      <span
        title="Stock inicial"
        className="px-3 py-1 rounded-full bg-[#1A1A22] text-white text-xs border border-[#2A2A32]"
      >
        stock
      </span>
    </div>

    <p className="text-xs text-gray-500">
      Con estas 3 columnas ya podés importar tus productos.
    </p>
  </div>

  <div className="mb-5">
    <p className="text-xs uppercase tracking-wide text-gray-500 mb-2">
      Columnas opcionales
    </p>

    <div className="flex flex-wrap gap-2 mb-3">
      <span
        title="Unidad de venta, por ejemplo: unidad, kg, litro o pack"
        className="px-3 py-1 rounded-full bg-[#121826] text-blue-300 text-xs border border-[#24304A]"
      >
        unit
      </span>

      <span
        title="Código interno del producto, por ejemplo: VEL-202"
        className="px-3 py-1 rounded-full bg-[#1A1426] text-purple-300 text-xs border border-[#34264A]"
      >
        code
      </span>

      <span
        title="Stock mínimo para que Arcana te avise cuando el producto esté bajo"
        className="px-3 py-1 rounded-full bg-[#20180F] text-yellow-300 text-xs border border-[#4A3A22]"
      >
        min_stock_yellow
      </span>
    </div>

    <p className="text-xs text-gray-500">
      Si no completás estas columnas, Arcana igual puede importar tu archivo.
    </p>
  </div>

  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
    <div className="bg-[#101522] border border-[#1D2740] rounded-xl p-4">
      <p className="text-sm text-white font-medium mb-1">Qué hace cada campo</p>
      <ul className="space-y-1 text-xs text-gray-400">
        <li><span className="text-white">name:</span> nombre del producto</li>
        <li><span className="text-white">price:</span> precio de venta</li>
        <li><span className="text-white">stock:</span> cantidad inicial</li>
        <li><span className="text-white">unit:</span> unidad de venta</li>
        <li><span className="text-white">code:</span> código interno del producto</li>
        <li><span className="text-white">min_stock_yellow:</span> alerta de stock mínimo</li>
      </ul>
    </div>

    <div className="bg-[#0F1A14] border border-[#1F3A2A] rounded-xl p-4">
      <p className="text-sm text-white font-medium mb-1">Consejo para empezar</p>
      <p className="text-xs text-gray-300 leading-5">
        Si recién empezás, usá solo <span className="text-white font-medium">name</span>,{" "}
        <span className="text-white font-medium">price</span> y{" "}
        <span className="text-white font-medium">stock</span>.
        Después podés completar el resto desde Arcana o en una próxima importación.
      </p>
    </div>
  </div>

  <p className="text-xs text-gray-500">
    Importante: una fila por producto y sin cambiar los nombres de las columnas.
  </p>
</div>
    </div>
  </div>
)}

    </div>
{isOpen && (
<div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
  <div className="bg-[#14141A] border border-[#1F1F24] rounded-2xl w-full max-w-md max-h-[90vh] flex flex-col overflow-hidden">
      <div className="p-5 md:p-8 border-b border-[#1F1F24]">
  <h2 className="text-2xl font-semibold text-white">
    Nuevo producto
  </h2>
</div>

<div className="p-5 md:p-8 space-y-5 overflow-y-auto flex-1 min-h-0">

        {/* Nombre */}
<div className="space-y-1">
  <label className="text-sm text-gray-400">
    Nombre del producto
  </label>

  <input
    value={newProductName}
    onChange={(e) => setNewProductName(e.target.value)}
    placeholder="Ej: Coca Cola 500cc"
    className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
    focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
  />

  <p className="text-xs text-gray-500">
    Ej: Coca Cola 500cc, Yerba 1kg, Papas fritas
  </p>
</div>

{/* Tipo de venta */}
<div className="space-y-2">

  <label className="text-sm text-gray-400">
    Tipo de venta
  </label>

  <div className="grid grid-cols-1 gap-2">

    <label className="flex items-center gap-3 bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 cursor-pointer">
      <input
        type="radio"
        checked={newSaleType === 'unit'}
        onChange={() => {
          setNewSaleType('unit')
          setNewUnitBase('unidad')
        }}
      />

      <div>
        <p className="text-sm text-white font-medium">
          Unidad / paquete
        </p>

        <p className="text-xs text-gray-500">
          Ej: Coca Cola 500cc, Galletas 600g, Yerba 1kg
        </p>
      </div>
    </label>

    <label className="flex items-center gap-3 bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 cursor-pointer">
      <input
        type="radio"
        checked={newSaleType === 'weight'}
        onChange={() => {
          setNewSaleType('weight')
          setNewUnitBase('kg')
          setNewUnit('kg')
          setNewPriceBy('kg')
        }}
      />

      <div>
        <p className="text-sm text-white font-medium">
          Peso fraccionado
        </p>

        <p className="text-xs text-gray-500">
          Ej: Queso, Papas fritas, Caramelos, Frutos secos
        </p>
      </div>
    </label>

  </div>

</div>

{newSaleType === 'weight' && (
  <div className="space-y-2">
    <label className="text-sm text-gray-400">
      Precio cargado por
    </label>

    <div className="grid grid-cols-2 gap-2">
      <label className="flex items-center gap-2 bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 cursor-pointer">
        <input
          type="radio"
          checked={newPriceBy === 'kg'}
          onChange={() => setNewPriceBy('kg')}
        />
        <span className="text-sm text-white">Kilo</span>
      </label>

      <label className="flex items-center gap-2 bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 cursor-pointer">
        <input
          type="radio"
          checked={newPriceBy === '100g'}
          onChange={() => setNewPriceBy('100g')}
        />
        <span className="text-sm text-white">100 gramos</span>
      </label>
    </div>

    <p className="text-xs text-gray-500">
      Ej: si el queso vale $1.300 cada 100g, elegí “100 gramos”.
    </p>
  </div>
)}

{newSaleType === 'weight' && (
  <div className="bg-[#0B0B10] border border-[#2A2A32] rounded-2xl p-4 space-y-4">

    <div>
      <p className="text-sm text-white font-semibold">
        Compra del producto
      </p>
      <p className="text-xs text-gray-500">
        Arcana usa estos datos para calcular el costo real y el margen.
      </p>
    </div>

    <div className="space-y-1">
      <label className="text-sm text-gray-400">
        Peso del paquete comprado
      </label>

      <input
        type="text"
        value={newPackageWeightKg}
        onChange={(e) => setNewPackageWeightKg(e.target.value)}
        placeholder="Ej: 5"
        className="w-full bg-[#101018] border border-[#2A2A32] rounded-xl p-3 text-white"
      />

      <p className="text-xs text-gray-500">
        Ej: si compraste una horma de 5kg, escribí 5.
      </p>
    </div>

    <div className="space-y-1">
      <label className="text-sm text-gray-400">
        Costo total del paquete
      </label>

      <div className="relative">
        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">
          $
        </span>

        <input
          type="text"
          value={newPackageCost}
          onChange={(e) => setNewPackageCost(formatMoneyInput(e.target.value))}
          placeholder="Ej: 12.000"
          className="w-full bg-[#101018] border border-[#2A2A32] rounded-xl p-3 pl-8 text-white"
        />
      </div>

      <p className="text-xs text-gray-500">
        Es lo que pagaste por el paquete completo.
      </p>
    </div>

  </div>
)}


        {/* Unidad */}
        <div className="space-y-1">
          <label className="text-sm text-gray-400">
            Unidad de venta
          </label>
          <select
            value={newUnit}
            onChange={(e) => setNewUnit(e.target.value)}
            className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
            focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
          >
            <option value="unidad">Unidad</option>
            <option value="kg">Kilo</option>
            <option value="litro">Litro</option>
            <option value="pack">Pack</option>
          </select>
        </div>

        {/* Precio */}
        <div className="space-y-1">
         <label className="text-sm text-gray-400">
  {newSaleType === 'weight'
    ? `Precio de venta por ${newPriceBy === '100g' ? '100g' : 'kg'}`
    : 'Precio de venta'}
</label>

          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">
              $
            </span>

            <input
              type="text"
              placeholder="Ej: 15000"
              value={newPrice}
              onChange={(e) => setNewPrice(formatMoneyInput(e.target.value))}
              className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl 
              p-3 pl-8 text-white
              focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
            />
          </div>
        </div>

{/* Proveedor */}
<div className="space-y-1">
  <label className="text-sm text-gray-400">
    Proveedor
  </label>

  <select
    value={newSupplierId}
    onChange={(e) => setNewSupplierId(e.target.value)}
    className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
    focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
  >
    <option value="">Sin proveedor</option>
    {suppliers.map((supplier) => (
      <option key={supplier.id} value={supplier.id}>
        {supplier.name}
      </option>
    ))}
  </select>
</div>

{/* Costo real */}
{newSaleType !== 'weight' && (
  <div className="space-y-1">
    <label className="text-sm text-gray-400">
      Costo de compra
    </label>

  <div className="relative">
    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">
      $
    </span>

    <input
      type="text"
      placeholder="Ej: 9000"
      value={newCostPrice}
      onChange={(e) => setNewCostPrice(formatMoneyInput(e.target.value))}
      className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl 
      p-3 pl-8 text-white
      focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
    />
  </div>
    </div>
)}

 {parseMoney(newPrice) > 0 && parseMoney(newCostPrice) > 0 && (
  <p className="text-xs text-green-400">
    Margen estimado: $
    {(parseMoney(newPrice) - parseMoney(newCostPrice)).toLocaleString()}
  </p>
)}
</div>

        {/* Stock inicial */}
        <div className="space-y-1">
          <label className="text-sm text-gray-400">
            {newSaleType === 'weight'
  ? 'Stock inicial (kg disponibles)'
  : 'Stock inicial (unidades)'}
          </label>
          <input
            type="number"
            placeholder={newSaleType === 'weight' ? 'Ej: 5' : 'Ej: 24'}
            value={newStock}
            onChange={(e) => setNewStock(e.target.value)}
            className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
            focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
          />
        </div>

        {/* Stock mínimo */}
        <div className="space-y-1">
          <label className="text-sm text-gray-400">
            {newSaleType === 'weight'
  ? 'Stock mínimo (kg para alerta)'
  : 'Stock mínimo (unidades para alerta)'}
          </label>
          <input
            type="number"
            min={1}
            placeholder={newSaleType === 'weight' ? 'Ej: 2' : 'Ej: 5'}
            value={newMinStock}
            onChange={(e) => setNewMinStock(e.target.value)}
          
            className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
            focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
          />
        </div>

{/* Código interno */}
<div className="space-y-1">
  <label className="text-sm text-gray-400">
    Código del producto (opcional)
  </label>

  <input
    value={newCode}
    onChange={(e) => setNewCode(e.target.value)}
    placeholder="Ej: VEL-202"
    className="w-full bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
    focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
  />
</div>

{/* Barcode */}

<div className="space-y-1">
  <label className="text-sm text-gray-400">
    Código de barras (opcional)
  </label>

  <div className="flex gap-2">

    <input
      value={newBarcode}
      onChange={(e) => setNewBarcode(e.target.value)}
      placeholder="Ej: 7791234567890"
      className="flex-1 bg-[#0B0B10] border border-[#2A2A32] rounded-xl p-3 text-white
      focus:outline-none focus:ring-2 focus:ring-[#1F6BFF]/40 transition"
    />

    <button
      type="button"
      onClick={generateEAN13}
      className="px-3 bg-[#2A2A32] rounded-xl hover:bg-[#333]"
    >
      ⚡ Generar
    </button>

  </div>
</div>

        {/* Activo */}
        <div className="flex items-center gap-3 pt-2">
          <input
            type="checkbox"
            checked={newActive}
            onChange={(e) => setNewActive(e.target.checked)}
          />
          <label className="text-sm text-gray-400">
            Producto activo
          </label>
        </div>

      </div>

      {/* Botones */}
      <div className="p-5 md:p-6 border-t border-[#1F1F24] bg-[#14141A] flex flex-col-reverse sm:flex-row justify-end gap-3">
        <button
          onClick={() => setIsOpen(false)}
          className="w-full sm:w-auto px-4 py-2 rounded-xl border border-[#2A2A32] bg-[#1A1A22] text-white hover:bg-[#22222B] hover:border-[#3A3A48] transition"
        >
          Cancelar
        </button>

        <button
          onClick={createProduct}
          className="w-full sm:w-auto bg-[#1F6BFF] hover:bg-[#2E7BFF] transition px-5 py-2 rounded-xl font-semibold"
        >
          Guardar
        </button>
            </div>
    </div>
  
)}
  </div>

)
}
